# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["gplearn_sgpa"]

[project]
name = "gplearn_sgpa"
version = "1.0.0"
readme = "README.rst"
dependencies = []
